/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package procesadordelenguaje.Interfaces;

import java.util.List;
import javax.swing.JFrame;
import procesadordelenguaje.JFLAP;

/**
 *
 * @author Meusz
 */
public class CoreMenu extends javax.swing.JFrame {

    private String ER;
    private JFrame main;
    private JFLAP jflap = new JFLAP();
    private String traduccion;
    private List<Character> alfabeto;

    /**
     * Creates new form Core
     */
    public CoreMenu(String ER, JFrame main) {
        this.ER = ER;
        this.traduccion = jflap.TraducirERJFLAP(ER);
        this.main = main;
        this.alfabeto = jflap.ObtenerAlfabeto(traduccion);
        initComponents();
        RegularExpressionLabel.setText(ER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegularExpressionLabel = new javax.swing.JLabel();
        ER_to_JFLAP = new javax.swing.JButton();
        ME = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Consola = new javax.swing.JTextArea();
        VariablesNumberJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        VariablesLengthJTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        RegularExpressionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ER_to_JFLAP.setText("Traduccion de ER a JFLAP");
        ER_to_JFLAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ER_to_JFLAPActionPerformed(evt);
            }
        });

        ME.setText("Dar todas las posibles cadenas de texto de entradas válidas");
        ME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Consola.setEditable(false);
        Consola.setColumns(20);
        Consola.setRows(5);
        jScrollPane1.setViewportView(Consola);

        jLabel1.setText("Numero Maximo Cadenas");

        jLabel2.setText("Logitud de las cadenas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(Back)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RegularExpressionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ME)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(VariablesNumberJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VariablesLengthJTextField)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(107, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ER_to_JFLAP)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegularExpressionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ER_to_JFLAP)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VariablesNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ME)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addComponent(VariablesLengthJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Back)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ER_to_JFLAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ER_to_JFLAPActionPerformed
        Consola.setText(traduccion);

    }//GEN-LAST:event_ER_to_JFLAPActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        main.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void MEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEActionPerformed
        try{
            int length = Integer.parseInt(VariablesLengthJTextField.getText());
            int number = Integer.parseInt(VariablesNumberJTextField.getText());
            if(length<=0 || number<= 0){
                Consola.setText("ERROR: Los valores introducidos en los recuadros han de ser superiores a 0");
            }else{
                new MatrixAFDInput(number,length,alfabeto,ER,this).setVisible(true);
                this.setVisible(false);
            }
        }catch(Exception e){
            Consola.setText("ERROR: Los valores introducidos en los recuadros ha de ser de tipo numerico");
        }
        

    }//GEN-LAST:event_MEActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextArea Consola;
    private javax.swing.JButton ER_to_JFLAP;
    private javax.swing.JButton ME;
    private javax.swing.JLabel RegularExpressionLabel;
    private javax.swing.JTextField VariablesLengthJTextField;
    private javax.swing.JTextField VariablesNumberJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
